### ISSUE TITLE
Support DRF 3.x

### ISSUE THREAD

**Issue by postfalk** [bkg/django-spillway#16]
Please test django-spillway against the newer packages. I think there are some adaptions necessary. Thank you

**Comment by postfalk** [comment]
Another issue that needs to be solved before migration to DRF 3.0 is to switch from ```model``` properties to ```queryset``` and from ```model_serializers``` to ```serializer_classes``` (?). Never mind just taking a quick note here for future reference. However, that does not seem to be urgent.

**Comment by bkg** [comment]
We found a workaround for migrations. The automatic migration generation breaks so some manual intervention is required here, just create the migration script with the `upload_to` file field function defined as a module level function and all is well.

**Comment by bkg** [comment]
Django 1.7 has been supported here for quite some time so let's revise the title.

**Comment by bkg** [comment]
DRF 3.0.5 is supported as of 9f2b1b6e87018551b03fd9b904fcde169a50d8ed

**Comment by postfalk** [comment]
@bkg I think that is not fully solved. My test won't work because the migration (succesfully generated) does not seem to work. Some tables are missing.

**Comment by bkg** [comment]
Which tables are missing? If it's anything besides the table corresponding to `RasterStore`, then it sounds unrelated.

Let's keep the follow up at https://github.com/berkeley-gif/bee/issues/280 since this issue is not specifically about migrations.

**Comment by postfalk** [comment]
No its more like the migration doesn't run at all. Seems to be a bigger
issue. The one for the app that does not uses spillway works fine.
Falk

On Thu, Jun 4, 2015 at 4:03 PM, Brian Galey <notifications@github.com>
wrote:

> Which tables are missing? If it's anything besides the table corresponding
> to RasterStore, then it sounds unrelated.
>
> Let's keep the follow up at berkeley-gif/bee#280
> <https://github.com/berkeley-gif/bee/issues/280> since this issue is not
> specifically about migrations.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bkg/django-spillway/issues/16#issuecomment-109083467>.
>



-- 
Falk Schuetzenmeister, PhD
Web Application Developer
Geospatial Innovation Facility <http://gif.berkeley.edu/>

University of California Berkeley
111 Mulford Hall
94720 Berkeley, CA

schuetzenmeister@berkeley.edu
1-510-642-4897

**Comment by postfalk** [comment]
I did not fix the migration yet (I have to dig a little bit deeper) but I managed to run the tests without running the migrations (which does not make a lot of sense anyway).
