### ISSUE TITLE
Question about GeoQuerySetFilter

### ISSUE THREAD

**Issue by postfalk** [bkg/django-spillway#17]
I am not sure whether the approach to reproject, simplify, and define precision in a FilterBackend really works across the board. Since FilterBackends are meant for filtering QuerySets and not so much for manipulating the objects within a QuerySet.

~~It doesn't seem to work for DetailViews because FilterBackends are not applied. The method ```filter_queryset``` simply does not exist.~~

Don't you think reprojection, simplification, and precision belong into the serialization since it influences how a very flexible geometry object will be displayed eventually. That is where we had it before. 

Making it part of the QuerySet has the huge advantage that PostGIS can do the work and there is also  the option to consider DetailViews as lists with a single element. 

We could also add the application of FilterBackends to DetailView.

**Comment by bkg** [comment]
Well, conceptually I think of these operations as a filtering of the geometry.
I see this filter backend as a more generic way to call `GeoQuerySet` methods
which are separate from serialization. This also provides for more streamlined
handling of model instances vs. querysets in either the detail or list views.

PostGIS is in fact doing the work here whether we request a detail or list
view.

Does the current usage complicate the setup for your application in some way?

**Comment by postfalk** [comment]
I do not think so. Just a question that occurred along the way.

On Tue, Jan 6, 2015 at 4:03 PM, Brian Galey <notifications@github.com>
wrote:

> Well, conceptually I think of these operations as a filtering of the
> geometry.
> I see this filter backend as a more generic way to call GeoQuerySet
> methods
> which are separate from serialization. This also provides for more
> streamlined
> handling of model instances vs. querysets in either the detail or list
> views.
>
> PostGIS is in fact doing the work here whether we request a detail or list
> view.
>
> Does the current usage complicate the setup for your application in some
> way?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bkg/django-spillway/issues/17#issuecomment-68957544>.
>



-- 
Falk Schuetzenmeister, PhD
Web Application Developer
Geospatial Innovation Facility <http://gif.berkeley.edu/>

University of California Berkeley
111 Mulford Hall
94720 Berkeley, CA

schuetzenmeister@berkeley.edu
1-510-642-4897

**Comment by bkg** [comment]
Okay, closing this out then.
