### ISSUE TITLE
Alter serializer based on selected renderer

### ISSUE THREAD

**Issue by postfalk** [bkg/django-spillway#24]
I am trying to pick the serializer dependant on whether the renderer is defined in spillway or somewhere else. I need this currently to avoid re-serialization or breaking changes to the API.

That is what I came up with (and it works):

```python

if 'spillway' in inspect.getmodule(self.request.accepted_renderer).__name__:
    # override serialization settings here
    pass
else:
    pass

```

Thoughts?

I might remove this later when I have a breaking v2 version of the API.

**Comment by bkg** [comment]
You probably don't want to go that route as it introduces added complexity and 
rigidity. What is the rationale?

**Comment by postfalk** [comment]
Well, the rationale is implementing spillway without breaking the existing
API.

On Thu, Feb 5, 2015 at 11:38 AM, Brian Galey <notifications@github.com>
wrote:

> You probably don't want to go that route as it introduces added complexity
> and
> rigidity. What is the rationale?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bkg/django-spillway/issues/24#issuecomment-73111658>.
>



-- 
Falk Schuetzenmeister, PhD
Web Application Developer
Geospatial Innovation Facility <http://gif.berkeley.edu/>

University of California Berkeley
111 Mulford Hall
94720 Berkeley, CA

schuetzenmeister@berkeley.edu
1-510-642-4897

**Comment by postfalk** [comment]
There is the unsolved issue that Geojson uses a different serialization
than other flavors of JSON and the DRF default (assuming model
serialization here).

On Thu, Feb 5, 2015 at 12:04 PM, Falk Schuetzenmeister <
schuetzenmeister@berkeley.edu> wrote:

> Well, the rationale is implementing spillway without breaking the existing
> API.
>
> On Thu, Feb 5, 2015 at 11:38 AM, Brian Galey <notifications@github.com>
> wrote:
>
>> You probably don't want to go that route as it introduces added
>> complexity and
>> rigidity. What is the rationale?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/bkg/django-spillway/issues/24#issuecomment-73111658>.
>>
>
>
>
> --
> Falk Schuetzenmeister, PhD
> Web Application Developer
> Geospatial Innovation Facility <http://gif.berkeley.edu/>
>
> University of California Berkeley
> 111 Mulford Hall
> 94720 Berkeley, CA
>
> schuetzenmeister@berkeley.edu
> 1-510-642-4897
>
>


-- 
Falk Schuetzenmeister, PhD
Web Application Developer
Geospatial Innovation Facility <http://gif.berkeley.edu/>

University of California Berkeley
111 Mulford Hall
94720 Berkeley, CA

schuetzenmeister@berkeley.edu
1-510-642-4897

**Comment by postfalk** [comment]
There is one much simpler example in the tutorials:

http://www.django-rest-framework.org/api-guide/renderers/#varying-behaviour-by-media-type

However, it does not recommend how to implement on class-based-views.

**Comment by bkg** [comment]
Okay, now that I understand the intent, you can get the behavior you are after by using `GeoModelSerializer` instead of `FeatureSerializer` as your default model serializer on your view and overriding `get_serializer_class()`. Something like this should do the trick:

``` Python
class GeoListView(BaseGeoView, ListAPIView): 
    model_serializer_class = serializers.GeoModelSerializer

    def get_serializer_class(self):
        serializer_class = super(GeoListView, self).get_serializer_class()
        if isinstance(self.request.accepted_renderer, GeoJSONRenderer):
            serializer_class = serializers.FeatureSerializer
        return serializer_class
```

I may consider adding this to `BaseGeoView` so let me think about that.

**Comment by postfalk** [comment]
That looks great. The one problem, I have to solve is how to deal with the
field selections on the serializers without duplicating the relative
complex definition of related fields as well as the option to select fields
with query params.

F.

On Fri, Feb 6, 2015 at 12:35 PM, Brian Galey <notifications@github.com>
wrote:

> Okay, now that I understand the intent, you can get the behavior you are
> after by using GeoModelSerializer instead of FeatureSerializer as your
> default model serializer on your view and overriding
> get_serializer_class(). Something like this should do the trick:
>
> class GeoListView(BaseGeoView, ListAPIView):
>     model_serializer_class = serializers.GeoModelSerializer
>
>     def get_serializer_class(self):
>         serializer_class = super(GeoListView, self).get_serializer_class()
>         if isinstance(self.request.accepted_renderer, GeoJSONRenderer):
>             serializer_class = serializers.FeatureSerializer
>         return serializer_class
>
> I may consider adding this to BaseGeoView so let me think about that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bkg/django-spillway/issues/24#issuecomment-73307727>.
>



-- 
Falk Schuetzenmeister, PhD
Web Application Developer
Geospatial Innovation Facility <http://gif.berkeley.edu/>

University of California Berkeley
111 Mulford Hall
94720 Berkeley, CA

schuetzenmeister@berkeley.edu
1-510-642-4897

**Comment by postfalk** [comment]
In my current experimental setup, I achieve BEE's current behavior by creating following chain of inheritance which I had to repeat for every single model to be serialized. 

What are ways to generalize this more ...

```python
from rest_framework import pagination
from spillway.generics import GeoListView
from spillway.renderers import GeoJSONRenderer
from spillway import serializers
from bee.base.models import DarwinCore
from bee.base.APIviews.views import ControlMixin


class DarwinCoreSerializerMixin(object):

    class Meta:
        model = DarwinCore
        # only a selection for demonstration purposes
        fields = ('record', 'geometry', 'genus', 'family', 'begin_date')

    # in BEE some serializer methods have been modified:
    # def to_native(self, obj):
    # def get_related_field(self, model_field, related_model, to_many):
    # def get_fields(self)
    #
    # Those changes have to be applied to both serializations


class TestSerializer(DarwinCoreSerializerMixin, serializers.GeoModelSerializer):
    pass


class TestFeatureSerializer(DarwinCoreSerializerMixin, serializers.FeatureSerializer):
    pass


class ObservationsList(ControlMixin, GeoListView):
    """New Spillway based observation view."""
    model = DarwinCore
    serializer_class = TestSerializer
    pagination_serializer_class = pagination.PaginationSerializer

    def get_serializer_class(self):
        serializer_class = super(ObservationsList, self).get_serializer_class()
        if isinstance(self.request.accepted_renderer, GeoJSONRenderer):
            serializer_class = TestFeatureSerializer
        return serializer_class

    def get_pagination_serializer(self, page):
        if isinstance(self.request.accepted_renderer, GeoJSONRenderer):
            self.pagination_serializer_class = serializers.PaginatedFeatureSerializer
        return super(ObservationsList, self).get_pagination_serializer(page)
```

**Comment by bkg** [comment]
Could you just have:

``` Python
class DarwinCoreSerializer(GeoModelSerializer):
    ...

class DarwinCoreFeatureSerializer(FeatureSerializer, DarwinCoreSerializer):
```

This would at least trim the total the number of classes you need, but it still doesn't scale well for very many models.

**Comment by postfalk** [comment]
That should work (saves 4 lines, and some inheritance;).
Falk

On Wed, Feb 11, 2015 at 11:25 AM, Brian Galey <notifications@github.com>
wrote:

> Could you just have:
>
> class DarwinCoreSerializer(GeoModelSerializer):
>     ...
> class DarwinCoreFeatureSerializer(FeatureSerializer, DarwinCoreSerializer):
>
> This would at least trim the total the number of classes you need, but it
> still doesn't scale well for very many models.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bkg/django-spillway/issues/24#issuecomment-73946463>.
>



-- 
Falk Schuetzenmeister, PhD
Web Application Developer
Geospatial Innovation Facility <http://gif.berkeley.edu/>

University of California Berkeley
111 Mulford Hall
94720 Berkeley, CA

schuetzenmeister@berkeley.edu
1-510-642-4897

**Comment by bkg** [comment]
Nice, sounds like you have a workable solution at this point so I will go ahead and close this out.

**Comment by postfalk** [comment]
Well, I have still big problems to integrate spillway and they are really
weird, I think we need to look at it together (I think there is some
interference with bee code going on which I cannot figure out).

But yes close this for now.

On Tue, Mar 10, 2015 at 12:17 PM, Brian Galey <notifications@github.com>
wrote:

> Nice, sounds like you have a workable solution at this point so I will go
> ahead and close this out.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bkg/django-spillway/issues/24#issuecomment-78126927>.
>



-- 
Falk Schuetzenmeister, PhD
Web Application Developer
Geospatial Innovation Facility <http://gif.berkeley.edu/>

University of California Berkeley
111 Mulford Hall
94720 Berkeley, CA

schuetzenmeister@berkeley.edu
1-510-642-4897
