### ISSUE TITLE
Implement crs property for paginated FeatureCollections

### ISSUE THREAD

**Issue by postfalk** [bkg/django-spillway#26]
As I understand the specification you can do:

```json
{"type": "FeatureCollection",
"crs": {},
"features": {}
}
```

**Comment by bkg** [comment]
Is this a bug or question, could you provide some more info please?

**Comment by postfalk** [comment]
Well, I am not sure whether it is a feature request, a bug, or a problem with my implementation but I am getting currently no crs for FeatureCollections (which should be handled on the pagination level). I have to look closer at your code to decide this question. I posted this here somewhat lazily in case, you might not have implemented this yet.

**Comment by bkg** [comment]
Thanks, I am able to reproduce a missing crs key for paginated feature collections. The non-paginated variant is working as expected.
