### ISSUE TITLE
Add to django-pacakges

### ISSUE THREAD

**Issue by tomchristie** [bkg/django-spillway#31]
Be good to see this on the REST framework grid of Django Packages... https://www.djangopackages.com/grids/g/django-rest-framework/

We could also link to it from the main docs (perhaps [here](http://www.django-rest-framework.org/api-guide/generic-views/#third-party-packages)?) if you provided a pull request with a brief description in the third party packages section.

**Comment by bkg** [comment]
Absolutely, thanks for the suggestion. I just added it to the package grid and I'll submit a pull for the REST framework docs soon.

**Comment by tomchristie** [comment]
Fab!
